version: '3.5'
services:
  api:
    image: eu.gcr.io/godlydpatruljen/server-hlf-dev:latest
#    depends_on:
#    - db
    env_file:
      - ./.env
    networks:
      godlydnett:
        ipv4_address: 172.12.17.10

###################################################
# If deploying locally, uncomment this 'db' block #
# as well as 'depends_on: - db' under 'api'       #
###################################################

#  db:
#    image: postgres:9.6
#    volumes:
#      - /var/lib/postgresql/data
#    ports:
#      - 5000:5432
#    environment:
#      - POSTGRES_USER=hlf
#      - POSTGRES_DB=godlyd
#      - PGDATA=/var/lib/postgresql/data/pgdata
#    logging:
#      driver: gcplogs

networks:
  godlydnett:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.12.17.0/24
