version: '3'
services:
  api:
    image: lydpatruljen/godlyd:latest
    ports:
      - 8080:8080
    depends_on:
      - db
    logging:
      driver: gcplogs
  db:
    image: postgres:9.6
    logging:
      driver: gcplogs
    volumes:
      - /var/lib/postgresql/data
    ports:
      - 5000:5432
    environment:
    - POSTGRES_USER=hlf
    - POSTGRES_DB=godlyd
    - PGDATA=/var/lib/postgresql/data/pgdata